/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SportRouteImport } from './routes/sport'
import { Route as BrainRouteImport } from './routes/brain'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiUsageRouteImport } from './routes/api/usage'
import { Route as ApiGenerateRouteImport } from './routes/api/generate'
import { Route as ApiEditRouteImport } from './routes/api/edit'
import { Route as ApiSportGenerateRouteImport } from './routes/api/sport/generate'
import { Route as ApiBrainTranslateRouteImport } from './routes/api/brain/translate'
import { Route as ApiBrainSaveRouteImport } from './routes/api/brain/save'
import { Route as ApiBrainListRouteImport } from './routes/api/brain/list'
import { Route as ApiBrainDeleteRouteImport } from './routes/api/brain/delete'

const SportRoute = SportRouteImport.update({
  id: '/sport',
  path: '/sport',
  getParentRoute: () => rootRouteImport,
} as any)
const BrainRoute = BrainRouteImport.update({
  id: '/brain',
  path: '/brain',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUsageRoute = ApiUsageRouteImport.update({
  id: '/api/usage',
  path: '/api/usage',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateRoute = ApiGenerateRouteImport.update({
  id: '/api/generate',
  path: '/api/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEditRoute = ApiEditRouteImport.update({
  id: '/api/edit',
  path: '/api/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSportGenerateRoute = ApiSportGenerateRouteImport.update({
  id: '/api/sport/generate',
  path: '/api/sport/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBrainTranslateRoute = ApiBrainTranslateRouteImport.update({
  id: '/api/brain/translate',
  path: '/api/brain/translate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBrainSaveRoute = ApiBrainSaveRouteImport.update({
  id: '/api/brain/save',
  path: '/api/brain/save',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBrainListRoute = ApiBrainListRouteImport.update({
  id: '/api/brain/list',
  path: '/api/brain/list',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBrainDeleteRoute = ApiBrainDeleteRouteImport.update({
  id: '/api/brain/delete',
  path: '/api/brain/delete',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/brain': typeof BrainRoute
  '/sport': typeof SportRoute
  '/api/edit': typeof ApiEditRoute
  '/api/generate': typeof ApiGenerateRoute
  '/api/usage': typeof ApiUsageRoute
  '/api/brain/delete': typeof ApiBrainDeleteRoute
  '/api/brain/list': typeof ApiBrainListRoute
  '/api/brain/save': typeof ApiBrainSaveRoute
  '/api/brain/translate': typeof ApiBrainTranslateRoute
  '/api/sport/generate': typeof ApiSportGenerateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/brain': typeof BrainRoute
  '/sport': typeof SportRoute
  '/api/edit': typeof ApiEditRoute
  '/api/generate': typeof ApiGenerateRoute
  '/api/usage': typeof ApiUsageRoute
  '/api/brain/delete': typeof ApiBrainDeleteRoute
  '/api/brain/list': typeof ApiBrainListRoute
  '/api/brain/save': typeof ApiBrainSaveRoute
  '/api/brain/translate': typeof ApiBrainTranslateRoute
  '/api/sport/generate': typeof ApiSportGenerateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/brain': typeof BrainRoute
  '/sport': typeof SportRoute
  '/api/edit': typeof ApiEditRoute
  '/api/generate': typeof ApiGenerateRoute
  '/api/usage': typeof ApiUsageRoute
  '/api/brain/delete': typeof ApiBrainDeleteRoute
  '/api/brain/list': typeof ApiBrainListRoute
  '/api/brain/save': typeof ApiBrainSaveRoute
  '/api/brain/translate': typeof ApiBrainTranslateRoute
  '/api/sport/generate': typeof ApiSportGenerateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/brain'
    | '/sport'
    | '/api/edit'
    | '/api/generate'
    | '/api/usage'
    | '/api/brain/delete'
    | '/api/brain/list'
    | '/api/brain/save'
    | '/api/brain/translate'
    | '/api/sport/generate'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/brain'
    | '/sport'
    | '/api/edit'
    | '/api/generate'
    | '/api/usage'
    | '/api/brain/delete'
    | '/api/brain/list'
    | '/api/brain/save'
    | '/api/brain/translate'
    | '/api/sport/generate'
  id:
    | '__root__'
    | '/'
    | '/brain'
    | '/sport'
    | '/api/edit'
    | '/api/generate'
    | '/api/usage'
    | '/api/brain/delete'
    | '/api/brain/list'
    | '/api/brain/save'
    | '/api/brain/translate'
    | '/api/sport/generate'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BrainRoute: typeof BrainRoute
  SportRoute: typeof SportRoute
  ApiEditRoute: typeof ApiEditRoute
  ApiGenerateRoute: typeof ApiGenerateRoute
  ApiUsageRoute: typeof ApiUsageRoute
  ApiBrainDeleteRoute: typeof ApiBrainDeleteRoute
  ApiBrainListRoute: typeof ApiBrainListRoute
  ApiBrainSaveRoute: typeof ApiBrainSaveRoute
  ApiBrainTranslateRoute: typeof ApiBrainTranslateRoute
  ApiSportGenerateRoute: typeof ApiSportGenerateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sport': {
      id: '/sport'
      path: '/sport'
      fullPath: '/sport'
      preLoaderRoute: typeof SportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brain': {
      id: '/brain'
      path: '/brain'
      fullPath: '/brain'
      preLoaderRoute: typeof BrainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/usage': {
      id: '/api/usage'
      path: '/api/usage'
      fullPath: '/api/usage'
      preLoaderRoute: typeof ApiUsageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate': {
      id: '/api/generate'
      path: '/api/generate'
      fullPath: '/api/generate'
      preLoaderRoute: typeof ApiGenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/edit': {
      id: '/api/edit'
      path: '/api/edit'
      fullPath: '/api/edit'
      preLoaderRoute: typeof ApiEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sport/generate': {
      id: '/api/sport/generate'
      path: '/api/sport/generate'
      fullPath: '/api/sport/generate'
      preLoaderRoute: typeof ApiSportGenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/brain/translate': {
      id: '/api/brain/translate'
      path: '/api/brain/translate'
      fullPath: '/api/brain/translate'
      preLoaderRoute: typeof ApiBrainTranslateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/brain/save': {
      id: '/api/brain/save'
      path: '/api/brain/save'
      fullPath: '/api/brain/save'
      preLoaderRoute: typeof ApiBrainSaveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/brain/list': {
      id: '/api/brain/list'
      path: '/api/brain/list'
      fullPath: '/api/brain/list'
      preLoaderRoute: typeof ApiBrainListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/brain/delete': {
      id: '/api/brain/delete'
      path: '/api/brain/delete'
      fullPath: '/api/brain/delete'
      preLoaderRoute: typeof ApiBrainDeleteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BrainRoute: BrainRoute,
  SportRoute: SportRoute,
  ApiEditRoute: ApiEditRoute,
  ApiGenerateRoute: ApiGenerateRoute,
  ApiUsageRoute: ApiUsageRoute,
  ApiBrainDeleteRoute: ApiBrainDeleteRoute,
  ApiBrainListRoute: ApiBrainListRoute,
  ApiBrainSaveRoute: ApiBrainSaveRoute,
  ApiBrainTranslateRoute: ApiBrainTranslateRoute,
  ApiSportGenerateRoute: ApiSportGenerateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
