/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SrtRouteImport } from './routes/srt'
import { Route as SportRouteImport } from './routes/sport'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as BrainRouteImport } from './routes/brain'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiUsageRouteImport } from './routes/api/usage'
import { Route as ApiGenerateRouteImport } from './routes/api/generate'
import { Route as ApiEditRouteImport } from './routes/api/edit'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as ApiSrtCorrectRouteImport } from './routes/api/srt/correct'
import { Route as ApiSportGenerateRouteImport } from './routes/api/sport/generate'
import { Route as ApiBrainTranslateRouteImport } from './routes/api/brain/translate'
import { Route as ApiBrainSaveRouteImport } from './routes/api/brain/save'
import { Route as ApiBrainListRouteImport } from './routes/api/brain/list'
import { Route as ApiBrainDeleteRouteImport } from './routes/api/brain/delete'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'

const SrtRoute = SrtRouteImport.update({
  id: '/srt',
  path: '/srt',
  getParentRoute: () => rootRouteImport,
} as any)
const SportRoute = SportRouteImport.update({
  id: '/sport',
  path: '/sport',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const BrainRoute = BrainRouteImport.update({
  id: '/brain',
  path: '/brain',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUsageRoute = ApiUsageRouteImport.update({
  id: '/api/usage',
  path: '/api/usage',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateRoute = ApiGenerateRouteImport.update({
  id: '/api/generate',
  path: '/api/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEditRoute = ApiEditRouteImport.update({
  id: '/api/edit',
  path: '/api/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiSrtCorrectRoute = ApiSrtCorrectRouteImport.update({
  id: '/api/srt/correct',
  path: '/api/srt/correct',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSportGenerateRoute = ApiSportGenerateRouteImport.update({
  id: '/api/sport/generate',
  path: '/api/sport/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBrainTranslateRoute = ApiBrainTranslateRouteImport.update({
  id: '/api/brain/translate',
  path: '/api/brain/translate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBrainSaveRoute = ApiBrainSaveRouteImport.update({
  id: '/api/brain/save',
  path: '/api/brain/save',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBrainListRoute = ApiBrainListRouteImport.update({
  id: '/api/brain/list',
  path: '/api/brain/list',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBrainDeleteRoute = ApiBrainDeleteRouteImport.update({
  id: '/api/brain/delete',
  path: '/api/brain/delete',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/brain': typeof BrainRoute
  '/mcp': typeof McpRoute
  '/sport': typeof SportRoute
  '/srt': typeof SrtRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/api/edit': typeof ApiEditRoute
  '/api/generate': typeof ApiGenerateRoute
  '/api/usage': typeof ApiUsageRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/brain/delete': typeof ApiBrainDeleteRoute
  '/api/brain/list': typeof ApiBrainListRoute
  '/api/brain/save': typeof ApiBrainSaveRoute
  '/api/brain/translate': typeof ApiBrainTranslateRoute
  '/api/sport/generate': typeof ApiSportGenerateRoute
  '/api/srt/correct': typeof ApiSrtCorrectRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/brain': typeof BrainRoute
  '/mcp': typeof McpRoute
  '/sport': typeof SportRoute
  '/srt': typeof SrtRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/api/edit': typeof ApiEditRoute
  '/api/generate': typeof ApiGenerateRoute
  '/api/usage': typeof ApiUsageRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/brain/delete': typeof ApiBrainDeleteRoute
  '/api/brain/list': typeof ApiBrainListRoute
  '/api/brain/save': typeof ApiBrainSaveRoute
  '/api/brain/translate': typeof ApiBrainTranslateRoute
  '/api/sport/generate': typeof ApiSportGenerateRoute
  '/api/srt/correct': typeof ApiSrtCorrectRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/brain': typeof BrainRoute
  '/mcp': typeof McpRoute
  '/sport': typeof SportRoute
  '/srt': typeof SrtRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/api/edit': typeof ApiEditRoute
  '/api/generate': typeof ApiGenerateRoute
  '/api/usage': typeof ApiUsageRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/brain/delete': typeof ApiBrainDeleteRoute
  '/api/brain/list': typeof ApiBrainListRoute
  '/api/brain/save': typeof ApiBrainSaveRoute
  '/api/brain/translate': typeof ApiBrainTranslateRoute
  '/api/sport/generate': typeof ApiSportGenerateRoute
  '/api/srt/correct': typeof ApiSrtCorrectRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/brain'
    | '/mcp'
    | '/sport'
    | '/srt'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/api/edit'
    | '/api/generate'
    | '/api/usage'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/api/brain/delete'
    | '/api/brain/list'
    | '/api/brain/save'
    | '/api/brain/translate'
    | '/api/sport/generate'
    | '/api/srt/correct'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/brain'
    | '/mcp'
    | '/sport'
    | '/srt'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/api/edit'
    | '/api/generate'
    | '/api/usage'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/api/brain/delete'
    | '/api/brain/list'
    | '/api/brain/save'
    | '/api/brain/translate'
    | '/api/sport/generate'
    | '/api/srt/correct'
  id:
    | '__root__'
    | '/'
    | '/brain'
    | '/mcp'
    | '/sport'
    | '/srt'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/api/edit'
    | '/api/generate'
    | '/api/usage'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/api/brain/delete'
    | '/api/brain/list'
    | '/api/brain/save'
    | '/api/brain/translate'
    | '/api/sport/generate'
    | '/api/srt/correct'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BrainRoute: typeof BrainRoute
  McpRoute: typeof McpRoute
  SportRoute: typeof SportRoute
  SrtRoute: typeof SrtRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  ApiEditRoute: typeof ApiEditRoute
  ApiGenerateRoute: typeof ApiGenerateRoute
  ApiUsageRoute: typeof ApiUsageRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiBrainDeleteRoute: typeof ApiBrainDeleteRoute
  ApiBrainListRoute: typeof ApiBrainListRoute
  ApiBrainSaveRoute: typeof ApiBrainSaveRoute
  ApiBrainTranslateRoute: typeof ApiBrainTranslateRoute
  ApiSportGenerateRoute: typeof ApiSportGenerateRoute
  ApiSrtCorrectRoute: typeof ApiSrtCorrectRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/srt': {
      id: '/srt'
      path: '/srt'
      fullPath: '/srt'
      preLoaderRoute: typeof SrtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sport': {
      id: '/sport'
      path: '/sport'
      fullPath: '/sport'
      preLoaderRoute: typeof SportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brain': {
      id: '/brain'
      path: '/brain'
      fullPath: '/brain'
      preLoaderRoute: typeof BrainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/usage': {
      id: '/api/usage'
      path: '/api/usage'
      fullPath: '/api/usage'
      preLoaderRoute: typeof ApiUsageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate': {
      id: '/api/generate'
      path: '/api/generate'
      fullPath: '/api/generate'
      preLoaderRoute: typeof ApiGenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/edit': {
      id: '/api/edit'
      path: '/api/edit'
      fullPath: '/api/edit'
      preLoaderRoute: typeof ApiEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/srt/correct': {
      id: '/api/srt/correct'
      path: '/api/srt/correct'
      fullPath: '/api/srt/correct'
      preLoaderRoute: typeof ApiSrtCorrectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sport/generate': {
      id: '/api/sport/generate'
      path: '/api/sport/generate'
      fullPath: '/api/sport/generate'
      preLoaderRoute: typeof ApiSportGenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/brain/translate': {
      id: '/api/brain/translate'
      path: '/api/brain/translate'
      fullPath: '/api/brain/translate'
      preLoaderRoute: typeof ApiBrainTranslateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/brain/save': {
      id: '/api/brain/save'
      path: '/api/brain/save'
      fullPath: '/api/brain/save'
      preLoaderRoute: typeof ApiBrainSaveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/brain/list': {
      id: '/api/brain/list'
      path: '/api/brain/list'
      fullPath: '/api/brain/list'
      preLoaderRoute: typeof ApiBrainListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/brain/delete': {
      id: '/api/brain/delete'
      path: '/api/brain/delete'
      fullPath: '/api/brain/delete'
      preLoaderRoute: typeof ApiBrainDeleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BrainRoute: BrainRoute,
  McpRoute: McpRoute,
  SportRoute: SportRoute,
  SrtRoute: SrtRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  ApiEditRoute: ApiEditRoute,
  ApiGenerateRoute: ApiGenerateRoute,
  ApiUsageRoute: ApiUsageRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiBrainDeleteRoute: ApiBrainDeleteRoute,
  ApiBrainListRoute: ApiBrainListRoute,
  ApiBrainSaveRoute: ApiBrainSaveRoute,
  ApiBrainTranslateRoute: ApiBrainTranslateRoute,
  ApiSportGenerateRoute: ApiSportGenerateRoute,
  ApiSrtCorrectRoute: ApiSrtCorrectRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
